server.port=8000

# JWT
api.security.jwt.secret-key=20YfbRclY55yz85WQvNybBEyUy7gcE3YvfK+6awpDec=
api.security.jwt.access-token-expiration=900000
api.security.jwt.refresh-token-expiration=86400000

# H2
spring.datasource.url=jdbc:h2:mem:shop;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Inicializaci\uFFFDn de datos
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always