spring.application.name=Web
server.port=8081

# Prueba de cambio de ruta.
# Las paginas Thymeleaf se adaptan bien gracias "@{/ruta}". Pero las estaticas (sobre-nosotros) no se puede adaptar.
### server.servlet.context-path=/shop

### server.servlet.context-path=/tienda