spring.application.name=Web
server.port=8080

<<<<<<< HEAD
# Prueba de cambio de ruta.
# Las paginas Thymeleaf se adaptan bien gracias "@{/ruta}". Pero las estaticas (sobre-nosotros) no se puede adaptar.
### server.servlet.context-path=/shop

### server.servlet.context-path=/tienda
=======
# Prueba de cambio de ruta (descomenta para probar contexto)
### server.servlet.context-path=/shop
### server.servlet.context-path=/tienda

# ?? H2 ? Cadena de conexión
spring.datasource.url=jdbc:h2:mem:shop;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ?? JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?? Consola web H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ?? Inicialización de datos
# Necesario para que data.sql se ejecute DESPUÉS de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.h2.console.settings.web-allow-others=true
>>>>>>> drm
